/*******************************************************************************
 * Copyright (c) 2025- The Band Gap Corporation
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Jay Jay Billings - Initial implementation
 *******************************************************************************/
package org.eclipse.ice.tasks.annotations;

import java.util.Arrays;
import java.util.Optional;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.TypeElement;
import javax.lang.model.util.Elements;
import org.eclipse.ice.tasks.IActionType;

/**
 * This is a utility class for validating IActionType values set in @Action
 * annotations.
 * 
 * The initial implementation was generated by Google Gemini 2.5 Pro by Jay Jay
 * Billings on 20250617 16:14.
 */
public class ActionTypeValidator {

	/**
	 * Semantically validates that a given path string resolves to a real, nested
	 * enum constant within the IActionType interface.
	 *
	 * @param typePath     The string from the annotation, e.g.,
	 *                     "IActionType.FUNCTION.JAVA".
	 * @param elementUtils The compiler utility for inspecting elements.
	 * @return true if the path is valid and resolves to an enum constant, false
	 *         otherwise.
	 */
	public boolean isValidActionType(String typePath, Elements elementUtils) {
		// Get the top-level interface element.
		final TypeElement baseElement = elementUtils.getTypeElement(IActionType.class.getCanonicalName());
		if (baseElement == null) {
			// This indicates a fundamental processor classpath issue.
			return false;
		}

		String[] pathParts = typePath.split("\\.");
		// If the provided path starts with "IActionType", ignore that part 
		// and start the search with the real members.
		if (pathParts.length > 1 && pathParts[0].equals(baseElement.getSimpleName().toString())) {
			pathParts = Arrays.copyOfRange(pathParts, 1, pathParts.length);
		}
		Element currentElement = baseElement;

		for (String part : pathParts) {
			Optional<? extends Element> nextElement = currentElement.getEnclosedElements().stream()
					.filter(e -> e.getSimpleName().toString().equals(part)).findFirst();

			if (nextElement.isPresent()) {
				currentElement = nextElement.get();
			} else {
				return false;
			}
		}

		boolean isEnumConstant = currentElement.getKind() == ElementKind.ENUM_CONSTANT;
		return isEnumConstant;
	}
}
