/*******************************************************************************
 * Copyright (c) 2025- The Band Gap Corporation
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * Jay Jay Billings - Initial implementation
 *******************************************************************************/
package org.eclipse.ice.tests.tasks.annotations;

import static com.google.testing.compile.CompilationSubject.assertThat;
import static com.google.testing.compile.Compiler.javac;

import org.eclipse.ice.dev.annotations.processors.DataElementProcessor;
import org.eclipse.ice.tasks.annotations.ActionFactoryProcessor;
import org.eclipse.ice.tasks.annotations.ActionProcessor;
import org.junit.jupiter.api.Test;

import com.google.testing.compile.Compilation;
import com.google.testing.compile.JavaFileObjects;

/**
 * This is a unit test for the ActionProcessor. It uses Google's compile-testing
 * library to verify that the annotation processor generates the correct source
 * files based on annotated input files.
 * 
 * It was partially generated by Google Gemini 2.5 Pro on 20250619 20:51.
 * 
 * * @author Jay Jay Billings
 */
class ActionProcessorTest {

	/**
	 * This test verifies that a simple Action class is generated correctly from a
	 * mock class annotated with @Action.
	 */
	@Test
	void testBasicMockActionGeneration() {
		Compilation compilation = javac().withProcessors(new ActionProcessor(), new ActionFactoryProcessor())
				.compile(JavaFileObjects.forResource("input/MessageMock.java"));

		// Assert that the compilation was successful
		assertThat(compilation).succeeded();

		// Assert that the compiler generated the expected Action source file
		assertThat(compilation).generatedSourceFile("org.eclipse.ice.tests.tasks.annotations.MessageMockAction")
				.hasSourceEquivalentTo(JavaFileObjects.forResource("expectedOutput/MessageMockAction.java"));
		// Assert that the compiler generated the expected ActionFactory source file
		assertThat(compilation).generatedSourceFile("org.eclipse.ice.tests.tasks.annotations.MessageMockActionFactory")
				.hasSourceEquivalentTo(JavaFileObjects.forResource("expectedOutput/MessageMockActionFactory.java"));
	}

	/**
	 * This test ensures that the ActionProcessor can generate an Action that depends
	 * on another generated type (a DataElement). It runs both the ActionProcessor
	 * and the DataElementProcessor in the same compilation task.
	 */
	@Test
	void testWithGeneratedDataElementDependency() {
		Compilation compilation = javac().withProcessors(new ActionProcessor(), new DataElementProcessor(), new ActionFactoryProcessor())
				.compile(JavaFileObjects.forResource("input/ActionProcessorTestHandler.java"));

		// Assert that the ActionProcessor generated the expected Action source file, which
		// depends on the generated TestDataElement
		assertThat(compilation)
				.generatedSourceFile("org.eclipse.ice.tests.tasks.annotations.ActionProcessorTestHandlerAction")
				.hasSourceEquivalentTo(JavaFileObjects
						.forResource("expectedOutput/ActionProcessorTestHandlerAction.java"));
		// Assert that the ActionProcessor generated the expected ActionFactory source file
		assertThat(compilation)
				.generatedSourceFile("org.eclipse.ice.tests.tasks.annotations.ActionProcessorTestHandlerActionFactory")
				.hasSourceEquivalentTo(JavaFileObjects
						.forResource("expectedOutput/ActionProcessorTestHandlerActionFactory.java"));
	}
}
