/*******************************************************************************
 * Copyright (c) 2025- The Band Gap Corporation
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Jay Jay Billings - Initial implementation
 *******************************************************************************/
package org.eclipse.ice.tests.tasks.annotations;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

import static com.google.testing.compile.CompilationSubject.assertThat;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.google.testing.compile.Compilation;
import com.google.testing.compile.Compiler;
import com.google.testing.compile.JavaFileObjects;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.RoundEnvironment;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.TypeElement;
import javax.tools.JavaFileObject;

import org.eclipse.ice.tasks.annotations.ActionTypeValidator;

import java.util.Set;

/**
 * This is a unit test for {@link ActionTypeValidator}.
 * 
 * The initial implementation was generated by Google Gemini 2.5 Pro by
 * Jay Jay Billings on 20250617 16:14.
 */
class ActionTypeValidatorTest {
	
	// Validator instance used for testing.
	ActionTypeValidator validator = new ActionTypeValidator();

	// A minimal IActionType for testing purposes. Using this fakes out the
	// full ActionProcessor infrastructure.
    private final JavaFileObject iActionTypeSource = JavaFileObjects.forSourceString("org.eclipse.ice.tasks.IActionType",
        """
        package org.eclipse.ice.tasks;
        public interface IActionType {
            enum FUNCTION implements IActionType { JAVA }
            enum HOOK implements IActionType { PRE, POST }
        }
        """
    );
	
    @Test
    void testValidPathReturnsTrue() {
        // This test processor will validate a known-good path.
        AbstractProcessor testProcessor = new AbstractProcessor() {
            @Override
            public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
                if (roundEnv.processingOver()) return true;
                boolean isValid = validator.isValidActionType("FUNCTION.JAVA", processingEnv.getElementUtils());
                assertTrue(isValid, "Expected 'FUNCTION.JAVA' to be a valid path.");
                return true;
            }
            @Override public Set<String> getSupportedAnnotationTypes() { return Set.of("*"); }
            @Override public SourceVersion getSupportedSourceVersion() { return SourceVersion.latest(); }
        };

        Compilation compilation = Compiler.javac().withProcessors(testProcessor).compile(iActionTypeSource);
        assertThat(compilation).succeeded();
    }

    @Test
    void testInvalidPathReturnsFalse() {
        // This processor tests a path that does not exist.
        AbstractProcessor testProcessor = new AbstractProcessor() {
            @Override
            public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
                if (roundEnv.processingOver()) return true;
                boolean isValid = validator.isValidActionType("FUNCTION.PYTHON", processingEnv.getElementUtils());
                assertFalse(isValid, "Expected 'FUNCTION.PYTHON' to be an invalid path.");
                return true;
            }
            @Override public Set<String> getSupportedAnnotationTypes() { return Set.of("*"); }
            @Override public SourceVersion getSupportedSourceVersion() { return SourceVersion.latest(); }
        };

        Compilation compilation = Compiler.javac().withProcessors(testProcessor).compile(iActionTypeSource);
        assertThat(compilation).succeeded();
    }
    
    @Test
    void testPathToNonEnumConstantReturnsFalse() {
        // This processor tests a path that points to an enum type, not a constant.
        AbstractProcessor testProcessor = new AbstractProcessor() {
            @Override
            public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
                if (roundEnv.processingOver()) return true;
                boolean isValid = validator.isValidActionType("HOOK", processingEnv.getElementUtils());
                assertFalse(isValid, "Expected 'HOOK' to be invalid as it is not an enum constant.");
                return true;
            }
            @Override public Set<String> getSupportedAnnotationTypes() { return Set.of("*"); }
            @Override public SourceVersion getSupportedSourceVersion() { return SourceVersion.latest(); }
        };

        Compilation compilation = Compiler.javac().withProcessors(testProcessor).compile(iActionTypeSource);
        assertThat(compilation).succeeded();
    }
}
