<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.eclipse.ice</groupId>
	<artifactId>org.eclipse.ice.workflows</artifactId>
	<version>3.0.0-SNAPSHOT</version>
	<name>org.eclipse.ice.workflows</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>17</java.version>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
	</properties>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.13.0</version>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.eclipse.ice</groupId>
							<artifactId>org.eclipse.ice.dev.annotations</artifactId>
							<version>3.0.0-SNAPSHOT</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.3.0</version>
			</plugin>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>3.1.2</version>
			</plugin>
			<!-- This creates the single executable jar (the "shaded jar") with
			all dependencies included.-->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.5.0</version>
				<executions>
					<execution>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<shadedArtifactAttached>true</shadedArtifactAttached>
							<transformers>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
									<mainClass>
										org.eclipse.ice.workflows.FileTransferWorkflowApp</mainClass>
								</transformer>
							</transformers>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<!-- This creates a single Jandex index for the shaded jar. -->
			<plugin>
				<groupId>io.smallrye</groupId>
				<artifactId>jandex-maven-plugin</artifactId>
				<version>3.2.3</version>
				<executions>
					<execution>
						<id>uberjar-index</id>
						<phase>package</phase>
						<goals>
							<goal>jandex-jar</goal>
						</goals>
						<configuration>
							<jar>
								${project.build.directory}/${project.build.finalName}-shaded.jar</jar>
							<includes>
								<include>org/eclipse/ice/**/*.class</include>
							</includes>
							<excludes>
								<exclude>org/eclipse/**/_private/*.class</exclude>
							</excludes>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>org.eclipse.ice</groupId>
			<artifactId>org.eclipse.ice.commands</artifactId>
			<version>3.0.0-SNAPSHOT</version>
		</dependency>
		<!-- JGraphT for workflow graphs of task dependencies -->
		<dependency>
			<groupId>org.jgrapht</groupId>
			<artifactId>jgrapht-core</artifactId>
			<version>1.5.2</version>
		</dependency>
		<dependency>
			<groupId>org.jgrapht</groupId>
			<artifactId>jgrapht-io</artifactId>
			<version>1.5.2</version>
		</dependency>
		<!-- Apache Commons Language bundle for tests -->
		<dependency>
			<groupId>org.netbeans.external</groupId>
			<artifactId>org-apache-commons-lang3</artifactId>
			<version>RELEASE130</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.ice</groupId>
			<artifactId>org.eclipse.ice.dev.annotations</artifactId>
			<version>3.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.ice</groupId>
			<artifactId>org.eclipse.ice.tasks</artifactId>
			<version>3.0.0-SNAPSHOT</version>
		</dependency>
	</dependencies>

</project>
