/******************************************************************************
 * Copyright (c) 2025- The Band Gap Corporation
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * Initial API and implementation and/or initial documentation - 
 * Jay Jay Billings
 *****************************************************************************/
package org.eclipse.ice.tests.data;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

import java.net.URI;
import java.net.URISyntaxException;

import org.eclipse.ice.data.Delegate;
import org.eclipse.ice.data.URIDelegate;
import org.junit.jupiter.api.Test;

/**
 * This class tests the Delegate wrapper class, primarily focusing on the
 * intended usage pattern of subclassing to provide initialization logic.
 * 
 * It was (mostly) generated by Google Gemini 2.5 Pro on 20250621 18:09.
 *
 * @author Jay Jay Billings
 */
class DelegateTest {

	// A concrete Delegate for String that initializes with a default value.
	private class StringDelegate extends Delegate<String> {
		public StringDelegate() {
			this.data = "The Good Life - Weezer";
		}
	}

	// A concrete Delegate for Integer that initializes with a default value.
	private class IntegerDelegate extends Delegate<Integer> {
		public IntegerDelegate() {
			// Special initialization technique for Integer
			this.data = 5;
		}
	}

	/**
	 * This test checks the Delegate subclassing pattern with a class that has a
	 * nullary constructor (String).
	 */
	@Test
	void testWithClassWithNullaryConstructor() {
		StringDelegate delegate = new StringDelegate();
		// Check that the value was set in the subclass constructor.
		assertEquals("The Good Life - Weezer", delegate.get());
		
		// Also test that the setter still works as expected.
		String newValue = "Hello, Delegate!";
		delegate.set(newValue);
		assertEquals(newValue, delegate.get());
	}

	/**
	 * This test checks the Delegate subclassing pattern with a boxed primitive type
	 * (Integer).
	 */
	@Test
	void testWithBoxedPrimitive() {
		IntegerDelegate delegate = new IntegerDelegate();
		// Check that the value was set in the subclass constructor.
		assertEquals(5, delegate.get());
		
		// Also test that the setter still works as expected.
		Integer newValue = 42;
		delegate.set(newValue);
		assertEquals(newValue, delegate.get());
	}

	/**
	 * This test checks the Delegate subclassing pattern with a class that does not
	 * have a public nullary constructor (URI).
	 */
	@Test
	void testWithClassWithoutNullaryConstructor() {
		URIDelegate delegate = new URIDelegate();
		// Check that the value was set in the subclass constructor.
		assertNotNull(delegate.get());
		assertEquals("https://www.eclipse.org/ice", delegate.get().toString());
		
		// Also test that the setter still works as expected.
		try {
			URI newUri = new URI("https://www.google.com");
			delegate.set(newUri);
			assertEquals(newUri, delegate.get());
		} catch (URISyntaxException e) {
			e.printStackTrace();
		}
	}

	/**
	 * This test ensures that a raw, non-subclassed delegate initially holds a null
	 * value until something is explicitly set.
	 */
	@Test
	void testRawDelegateInitialStateIsNull() {
		Delegate<Object> rawDelegate = new Delegate<>();
		assertNull(rawDelegate.get(), "A raw delegate should be null initially.");
	}
}
