/******************************************************************************
 * Copyright (c) 2025- The Band Gap Corporation
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Initial API and implementation and/or initial documentation - 
 *   Jay Jay Billings
 *****************************************************************************/
package org.eclipse.ice.tests.tasks.basics;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import org.eclipse.ice.data.URIDelegate;
import org.eclipse.ice.tasks.basics.LocalMover;
import org.eclipse.ice.tasks.basics.LocalMoverAction;
import org.eclipse.ice.tasks.basics.MoveData;
import org.eclipse.ice.tasks.basics.MoveDataFactory;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
/**
 * Unit test for LocalMoverAction. Mostly generated by Google Gemini 2.5 Pro on
 * 20250619 13:14.
 */
class LocalMoverActionTest {
	
	private LocalMoverAction moveAction;
    private MoveData moveData;

    @TempDir
    Path tempDir;

    private Path srcFile;
    private Path destFile;

    @BeforeEach
    public void setUp() throws Exception {
    	LocalMover mover = new LocalMover();
        moveAction = new LocalMoverAction(mover);
        MoveDataFactory moveDataFactory = new MoveDataFactory();
        moveData = moveDataFactory.build();
        
        // Create a source file with some content
        srcFile = tempDir.resolve("source.txt");
        Files.write(srcFile, "test content".getBytes());

        // Define the destination path
        destFile = tempDir.resolve("destination.txt");
    }

    @Test
    public void testRunSuccess() {
        // Configure the MoveDataElement with our temporary path URIs
    	URIDelegate src = moveData.getSrcDelegate();
    	URIDelegate dest = moveData.getDestDelegate();
        src.set(srcFile.toUri());
        dest.set(destFile.toUri());

        // Pre-conditions
        assertTrue(Files.exists(srcFile), "Source file should exist before move");
        assertFalse(Files.exists(destFile), "Destination file should not exist before move");

        // Execute the action and check the return value
        boolean result = moveAction.run(moveData);
        assertTrue(result, "Move action should return true on success");

        // Post-conditions
        assertFalse(Files.exists(srcFile), "Source file should not exist after move");
        assertTrue(Files.exists(destFile), "Destination file should exist after move");
        
        // Verify content was moved correctly
        try {
            String content = new String(Files.readAllBytes(destFile));
            assertEquals("test content", content);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Test
    public void testRunSourceNotFound() {
        // Configure the MoveDataElement with a non-existent source file URI
        Path nonExistentSrc = tempDir.resolve("nonExistent.txt");
    	URIDelegate src = moveData.getSrcDelegate();
    	URIDelegate dest = moveData.getDestDelegate();
    	src.set(nonExistentSrc.toUri());
    	dest.set(destFile.toUri());

        // Pre-condition
        assertFalse(Files.exists(nonExistentSrc), "Source file should not exist");
        
        // Execute the action and check the return value
        boolean result = moveAction.run(moveData);
        assertFalse(result, "Move action should return false when the source file does not exist.");
        
        // Post-condition: ensure no file was created at the destination
        assertFalse(Files.exists(destFile), "Destination file should not be created on failure.");
    }
}
